FROM node:8.1.3

RUN apt-get update \
    && apt-get install -y --no-install-recommends git \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /gs/server
WORKDIR /gs/server

COPY package.json yarn.lock ./

ENV NODE_ENV=development

RUN apt-get update \
    && apt-get install -y --no-install-recommends python \
    && yarn \
    && apt-get purge -y --auto-remove python \
    && rm -rf /var/lib/apt/lists/*

CMD ["yarn", "run", "watch"]
